spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sbb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: lldj
    password: lldj1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
